name: Fetch Odds

on:
  schedule:
    # Run every 12 minutes, 24/7 (7,200 calls/month - within 20K limit)
    - cron: '0,12,24,36,48 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-odds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Fetch NFL odds (Enhanced)
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      run: node fetch-odds.js
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add odds/
        git diff --staged --quiet || git commit -m "Update odds - $(date)"
        git push



































